# JS
cat "../extensions/build/extensions.js" > "./build/index.js"
cat "../../external_libs/notify.js"    >> "./build/index.js"
cat "./imports.js"                     >> "./build/index.js"
cat "./AddToCartControl.js"            >> "./build/index.js"
cat "../base_classes/HtmlControl.js"   >> "./build/index.js"
cat "./WineInfoTable.js"               >> "./build/index.js"
cat "./SearchResultTable.js"           >> "./build/index.js"
cat "./GiftWrapControl.js"             >> "./build/index.js"
cat "./PhotoControl.js"                >> "./build/index.js"
cat "./HeaderElement.js"               >> "./build/index.js"
cat "./AsideElement.js"                >> "./build/index.js"
cat "./FooterElement.js"               >> "./build/index.js"
cat "./HorizontallyScrollable.js"      >> "./build/index.js"
cat "./NewArrivalControl.js"           >> "./build/index.js"
cat "./RankingControl.js"              >> "./build/index.js"
cat "./NewInfoControl.js"              >> "./build/index.js"
cat "./ImporterControl.js"             >> "./build/index.js"
cat "./WineDetailTable.js"             >> "./build/index.js"
cat "./WineSetControl.js"              >> "./build/index.js"
cat "./WineSetDetail.js"               >> "./build/index.js"
cat "./AdvancedSearchControl.js"       >> "./build/index.js"
cat "./PageContents.js"                >> "./build/index.js"
cat "./index.js"                       >> "./build/index.js"

